@HostAddress = http://localhost:5225
@Version = v1

//Product API Tests

GET {{HostAddress}}/api/{{Version}}/getproducts
Accept: application/json

###

//GetById (excpected 200 if exists)
GET {{HostAddress}}/api/{{Version}}/getproduct/17
Accept: application/json

###
//GetById (excpected 502 bad request)
GET {{HostAddress}}/api/{{Version}}/getproduct/1712312
Accept: application/json

###
//Valid create (excpected 200)

POST {{HostAddress}}/api/{{Version}}/createproduct
Content-Type: application/json
Accept: application/json
{
  "title": "New ProductTest1",
  "price": 10,
  "description": "A description",
  "categoryId": 1,
  "images": ["https://i.imgur.com/QkIa5tT.jpeg"]
}

###
//Invalid create (expected 400 with field missing errros)

POST {{HostAddress}}/api/{{Version}}/createproduct
Content-Type: application/json
Accept: application/json
{
  "title": "",
  "price": 0,
  "description": "",
  "categoryId": 0,
  "images": []
}

###
//Images with empty string (excpected 400 with image error)

POST {{HostAddress}}/api/{{Version}}/createproduct
Content-Type: application/json
Accept: application/json
{
  "title": "New Product 2026-03-25-1117",
  "price": 10,
  "description": "A description",
  "categoryId": 1,
  "images": ["   "]
}


###

//Category API Tests  

//GetAll (excpected 200)
GET {{HostAddress}}/api/{{Version}}/getcategories
Accept: application/json

###

//GetById (excpected 200 if exists)
GET {{HostAddress}}/api/{{Version}}/getcategory/1
Accept: application/json


###
//GetById (excpected 502 bad request)
GET {{HostAddress}}/api/{{Version}}/getcategory/12391231
Accept: application/json

###
